<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui, viewport-fit=cover">';
echo '<title>TweaksDev22 Repo</title>';
echo '<link rel="stylesheet" href="css/pack.css">';
echo '<style>';
echo 'body, html{';
echo 'margin:0px;';
echo 'font-family:helvetica;';
echo 'overflow-x:hidden;';
echo 'height:100%;';
echo 'background-color:#101010';
echo '}';
echo '';
echo '.button{';
echo 'display:inline-block;';
echo 'width:80px;';
echo 'padding:10px;';
echo 'border-radius:5px;';
echo 'background-color:#e74f4f;';
echo 'margin:10px;';
echo 'color:white;';
echo 'text-decoration:none;';
echo 'font-weight:500;';
echo '}';
echo '</style>';
echo '';
echo '</head>';
echo '<body>';
echo '';
echo '<center>';
echo '<img style="width:100px;margin:10px;border-radius:20px;;margin-top:40px;" src="CydiaIcon.png">';
echo '<h1 style="margin:0px;font-size:25px;color:#fff;">TweaksDev22 Repo</h1>';
echo '<p style="margin:10px;font-size:15px;color:#fff;">My Tweaks & More..</p>';
echo '<a class="button" href="cydia://url/https://cydia.saurik.com/api/share#?source=https://tweaksdev22.github.io/Repo/">Add Repo</a>';
echo '</center>';
echo '';
echo '';
echo '';
echo '</body>';
echo '</html>';
?>
